<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Vtt.Scene.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vtt.Scene.Application\Vtt.Scene.Application.csproj" />
    <ProjectReference Include="..\Vtt.Scene.Domain\Vtt.Scene.Domain.csproj" />
  </ItemGroup>
</Project>
