<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Vtt.Edge.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Vtt.Edge.Application\Vtt.Edge.Application.csproj" />
    <ProjectReference Include="..\Vtt.Edge.Domain\Vtt.Edge.Domain.csproj" />
  </ItemGroup>
</Project>
